### ISSUE TITLE
In tasks name gets overwritten if task is moved to another column/list

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#19] opened 2020-02-25 20:35 UTC
How to reproduce:
We start with something like this. Two tasks in two separate columns with separate names for person responsible.
![image1](https://user-images.githubusercontent.com/8218499/75285244-2ca4b680-580e-11ea-9945-80695df30fb9.png)
Move one task so it is in the same column and we see the name gets changed.
![image2](https://user-images.githubusercontent.com/8218499/75285245-2d3d4d00-580e-11ea-90c1-c0ee97982b3d.png)

Current solution: refresh the webpage.

**Comment by Ingimarsson** [comment] 2020-02-25 22:12
Duplicate of #9

**Comment by Ingimarsson** [comment] 2020-02-25 22:36
Fix has been committed. Issue was that React Drag-and-drop recycles the Task components of each column and so rendering name must be done in componentDidUpdate()

**Closed as completed by Ingimarsson** 2020-02-25 22:36 UTC
Labels: bug
