### ISSUE TITLE
Can't create task for project.

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#22] opened 2020-03-01 11:06 UTC
Currently in pluto 3.1 users cannot create tasks within a project.

![image](https://user-images.githubusercontent.com/8218499/75624488-8dd0df00-5bac-11ea-9ec9-f1e1c3276da9.png)

It should look like this: 

![image](https://user-images.githubusercontent.com/8218499/75624508-b2c55200-5bac-11ea-9a9c-17f30c58a883.png)

**Comment by Ingimarsson** [comment] 2020-03-01 23:17
Duplicate of #7

**Closed as completed by Ingimarsson** 2020-03-01 23:17 UTC
